export const dataProperties = [
  {
    id: 1,
    location: "Chapinero, Bogotá, CO",
    price: 850000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie1.jpeg",
    star: 4.5,
    meters: 430,
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 2,
    location: "El Poblado, Medellín, CO",
    price: 650000000,
    bedrooms: 2,
    bathroom: 2,
    image: "propertie2.jpeg",
    star: 4,
    meters: 230,
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 3,
    location: "Ciudad Jardín, Cali, CO",
    price: 450000000,
    bedrooms: 5,
    bathroom: 2,
    image: "propertie3.jpeg",
    star: 5,
    meters: 90,
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 4,
    location: "Bello Horizonte, Barranquilla, CO",
    price: 380000000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie4.jpeg",
    star: 4.2,
    meters: 120,
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 5,
    location: "Bocagrande, Cartagena, CO",
    price: 750000000,
    bedrooms: 3,
    bathroom: 2,
    image: "propertie5.jpeg",
    star: 4.1,
    meters: 87,
    description:
      "En el corazón de la histórica Cartagena, te presentamos una oportunidad única de adquirir un espectacular apartamento que combina el encanto colonial con las comodidades modernas. Esta vivienda, ubicada en una zona exclusiva y bien comunicada, ofrece vistas impresionantes al mar Caribe...",
  },
  {
    id: 6,
    location: "Santa Bárbara, Bogotá, CO",
    price: 920000000,
    bedrooms: 4,
    bathroom: 3,
    image: "propertie6.jpeg",
    star: 3.7,
    meters: 220,
    description:
      "En el exclusivo sector de Santa Bárbara, presentamos este magnífico apartamento con acabados de lujo y una vista privilegiada a los cerros orientales...",
  },
  {
    id: 7,
    location: "Laureles, Medellín, CO",
    price: 580000000,
    bedrooms: 3,
    bathroom: 2,
    image: "propertie7.jpeg",
    star: 4.5,
    meters: 430,
    description:
      "En el tradicional barrio Laureles, encontrarás esta espaciosa casa que combina la calidez paisa con un diseño moderno y funcional...",
  },
  {
    id: 8,
    location: "Ciudad Jardín, Cali, CO",
    price: 480000000,
    bedrooms: 3,
    bathroom: 2,
    image: "propertie8.jpeg",
    star: 4.5,
    meters: 330,
    description:
      "En el sector más verde de Cali, presentamos esta hermosa casa con amplios jardines y espacios diseñados para disfrutar del clima tropical...",
  },
  {
    id: 9,
    location: "Rosales, Bogotá, CO",
    price: 1250000000,
    bedrooms: 4,
    bathroom: 4,
    image: "propertie9.jpeg",
    star: 4.5,
    meters: 500,
      description:
    "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 10,
    location: "Envigado, Medellín, CO",
    price: 680000000,
    bedrooms: 3,
    bathroom: 2,
    image: "propertie10.jpeg",
    star: 4.1,
    meters: 270,
    description:
      "Hermoso apartamento en Envigado con amplios espacios, excelente iluminación natural y acabados modernos. Ubicado en una zona residencial tranquila con fácil acceso a centros comerciales y al sistema de transporte público...",
  },
  {
    id: 11,
    location: "Usaquén, Bogotá, CO",
    price: 950000000,
    bedrooms: 4,
    bathroom: 3,
    image: "propertie11.jpeg",
    star: 5,
    meters: 430,
    description:
      "Exclusiva casa en Usaquén, con arquitectura colonial moderna, amplios espacios sociales y hermoso jardín interior. Cerca a la plaza principal y a los mejores restaurantes de la zona...",
  },
  {
    id: 12,
    location: "Granada, Cali, CO",
    price: 420000000,
    bedrooms: 3,
    bathroom: 2,
    image: "propertie12.jpeg",
    star: 3.9,
    meters: 176,
    description:
      "Moderno apartamento en el sector de Granada, con vista panorámica a la ciudad. Cuenta con acabados de lujo, zona social con piscina y gimnasio...",
  },
  {
    id: 13,
    location: "Castillogrande, Cartagena, CO",
    price: 1350000000,
    bedrooms: 4,
    bathroom: 4,
    image: "propertie13.jpeg",
    star: 4.8,
    meters: 290,
    description:
      "Espectacular apartamento frente al mar en Castillogrande, con vista panorámica al océano, amplias terrazas y acceso directo a la playa. Diseño contemporáneo con acabados de lujo...",
  },
  {
    id: 14,
    location: "Alto Prado, Barranquilla, CO",
    price: 580000000,
    bedrooms: 3,
    bathroom: 2,
    image: "propertie14.jpeg",
    star: 4.9,
    meters: 180,
    description:
      "Elegante apartamento en el tradicional barrio Alto Prado, completamente remodelado con acabados de primera. Cerca a los mejores colegios y centros comerciales...",
  },
  {
    id: 15,
    location: "Provenza, Medellín, CO",
    price: 750000000,
    bedrooms: 3,
    bathroom: 2,
    image: "propertie15.jpeg",
    star: 4.1,
    meters: 287,
    description:
      "Acogedor apartamento en el corazón de Provenza, zona gastronómica por excelencia. Espacios amplios, balcón con vista a la ciudad y excelente ubicación cerca a restaurantes y vida nocturna...",
  },
  {
    id: 16,
    location: "Cedritos, Bogotá, CO",
    price: 620000000,
    bedrooms: 3,
    bathroom: 2,
    image: "propertie16.jpeg",
    star: 4,
    meters: 290,
    description:
      "Amplio apartamento familiar en Cedritos, con excelente distribución, tres habitaciones, estudio y balcón. Ubicado cerca a parques, centros comerciales y principales vías de acceso...",
  }
];